# Generated by Django 5.0.6 on 2024-05-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Младшее звено 1-4 классы', 'Младшее звено 1-4 класс'), ('Среднее звено 5-7 классы', 'Среднее звено 5-7 классы'), ('Старшее звено 8-11 классы', 'Старшее звено 8-11 классы')], max_length=100, verbose_name='Наименование степени обучающихся (звена)')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Интеллектуальный квиз', 'Интеллектуальный квиз'), ('Музыкальный квиз', 'Музыкальный квиз'), ('Спортивное мероприятие', 'Спортивное мероприятие'), ('Классическая Мафия', 'Классическая Мафия'), ('Своя Игра', 'Своя Игра'), ('Интеллектуальная игра 100к1', 'Интеллектуальная игра 100к1'), ('Брейн-ринг', 'Брейн-ринг')], max_length=100, verbose_name='Наименование типа мероприятия')),
            ],
        ),
    ]
