# Generated by Django 5.0.6 on 2024-05-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0003_alter_profile_klass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_disbanded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество (если есть)'),
        ),
    ]
