# Generated by Django 5.0.6 on 2024-05-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0004_team_alter_profile_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_eventers', models.IntegerField(default=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField(blank=True, null=True)),
                ('EducationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.educationlevel')),
                ('EventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Start', models.DateField(blank=True, null=True)),
                ('Date_End', models.DateField(blank=True, null=True)),
                ('Responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Plan_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Date_Plan', models.DateField(blank=True, null=True)),
                ('Date_Fact', models.DateField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Eventers_Plan', models.IntegerField(blank=True, null=True)),
                ('Eventers_Fact', models.IntegerField(blank=True, null=True)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Diplom.event')),
                ('Event_Plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Diplom.event_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('Event_Plan_Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.event_plan_position')),
                ('Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.profile')),
                ('Team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.team')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField(blank=True, null=True)),
                ('Time_Submit', models.DateTimeField(blank=True, null=True)),
                ('Event_Plan_Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.event_plan_position')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.profile')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.post')),
            ],
        ),
        migrations.CreateModel(
            name='Team_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.team')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.TextField(blank=True, null=True)),
                ('Invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.invitation')),
                ('Team_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.team_list')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.profile')),
                ('Team_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.team_list')),
            ],
        ),
    ]
