# Generated by Django 5.0.6 on 2024-05-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0005_event_event_plan_event_plan_position_invitation_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='Team_Members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Diplom.team_members'),
        ),
    ]
