# Generated by Django 5.0.6 on 2024-05-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0006_invitation_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('На рассмотрении', 'На рассмотрении'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена'), ('Отменена', 'Отменена'), ('Посещено', 'Посещено')], default='На рассмотрении', max_length=255, verbose_name='Статус заявки')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/static/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/static/images'),
        ),
        migrations.CreateModel(
            name='InvitationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status_Date', models.DateField(auto_now_add=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.invitation')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.profile')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.status')),
            ],
        ),
    ]
