# Generated by Django 4.2.7 on 2024-05-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0008_alter_event_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.BooleanField(blank=True, null=True, verbose_name='Командное мероприятие'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
