# Generated by Django 4.2.7 on 2024-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0010_team_capitan_alter_results_team_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateField(blank=True, null=True),
        ),
    ]
